### ISSUE TITLE
VersionCode is empty?

### ISSUE THREAD

**Issue by zhenghx1105** [NeroBurner/googleplayupdater#3]
when I call detail method get the details.appDetails.versionCode value always is 0,versionstring is emtpy?

**Comment by NeroBurner** [comment]
This most probably happens because of a wrong android-id. Please get your android-id again and reset it in your config.py.

The original [android-checkin](https://github.com/nviennot/android-checkin) doesn't seem to work for me anymore, but I've tried an updated fork from [bcopos](https://github.com/bcopos/android-checkin).

I used the following commands to get my `android_id` (replace <email> <password> with your email and password):

```
git clone https://github.com/bcopos/android-checkin
cd android-checkin
java -Xbootclasspath/a:lib/httpcore-4.2.2.jar:lib/httpclient-4.2.2.jar:lib/httpmime-4.2.2.jar:lib/httpclient-cache-4.2.2.jar:lib/commons-logging-1.1.1.jar:lib/fluent-hc-4.2.2.jar:lib/protobuf-java-2.4.1.jar:lib/commons-codec-1.6.jar -jar android-checkin-jb.jar <email> <password>
```

Please report back and if it worked I'll update the README.md file

**Comment by zhenghx1105** [comment]
Unfortunately,I used your way to check android-id that it's correct in fact;I had no idea what wrong ahout it. when the versioncode is 0.I call download method return error code 500;Thank you for you response yet;

**Comment by NeroBurner** [comment]
Assuming all credentials are correct (email, password, android-id), then the versioncode 0 indicates, that the apk you searched for is not found by the googleplay-api. Maybe you misspelled the apk-name? Could you post a code-snipped on how you try to get the information for the apk and how you download it?

**Comment by zhenghx1105** [comment]
m = playstore_api.details(packagename)
doc = m.docV2
store_version_code = int(doc.details.appDetails.versionCode)

the apk-name is correct and the app is in the store; I got the appDetails is not None but  I didn't got theappDetails's versioncode ,versionstring ,installationSize propertys; i don't know why;
I tried to transformed to write with C# that I got the same fail result;
Thank you for you suggestion and helps!

**Comment by NeroBurner** [comment]
Could you tell me the full name of the apk you want to download so I can try it out myself?

**Comment by zhenghx1105** [comment]
com.google.android.gm  this app I was find on the google play store,it's exist;thanks!

**Comment by NeroBurner** [comment]
I was able to download the apk. My steps were:

```
git clone https://github.com/NeroBurner/googleplay-api
cd googleplay-api
virtualenv venv
source venv/bin/activate
pip install -e .
```

then edit the `config.py` with your credentials. Start the download-script (I use python2, for python3 see [README.md-python3-section](https://github.com/NeroBurner/googleplayupdater#python-3))

```
python2 download.py com.google.android.gm
Downloading to file com.google.android.gm_56008678.apk with size 12.3MB...
Done
```

Please try the steps and report back. Hope it works ;)

**Comment by zhenghx1105** [comment]
python download.py com.google.android.gm
Downloading to file com.google.android.gm_0.apk with size 0.0bytes...
Traceback (most recent call last):
  File "download.py", line 51, in <module>
    data = api.download(packagename, vc, ot)

Mmm....It does't work for me,I treid to use proxy But does't work to ;My guess is that the only one reson is I’m Chinese.
Thank for you helps;

**Comment by NeroBurner** [comment]
If I change my android-id to something wrong (just deleted one digit) then I also get the following:

```
python2 download.py com.google.android.gm
Downloading to file com.google.android.gm_0.apk with size 0.0bytes...
Traceback (most recent call last):
  File "download.py", line 46, in <module>
    data = api.download(packagename, vc, ot)
  File "/home/nero/repos/test/googleplay-api/googleplay_api/googleplay.py", line 315, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

For me it looks like a wrong android-id, but I don't know enough of the chinese firewall to say for sure. You could try a VPN or try it on a VPS (for example from digitalocean)

**Comment by zhenghx1105** [comment]
I will try some androidids from true devices;If it does't work yet.I had to try use vpn or on vps;
Forget my poor English! 
:)
Thank you for your patience and help all the time.

**Comment by NeroBurner** [comment]
you're welcome

closed: cannot reproduce
